server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Configuración de CORS si conectas un frontend (Angular, React, etc.)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      # Definición de rutas hacia los microservicios
      routes:
        # 1. Microservicio de Autenticación / Usuarios
        - id: auth-service
          uri: http://localhost:8081   # Ajusta al puerto de tu servicio de auth
          predicates:
            - Path=/api/v1/auth/**, /api/v1/roles/**

        # 2. Microservicio de Productos
        - id: products-service
          uri: http://localhost:8082   # Ajusta al puerto de tu servicio de productos
          predicates:
            - Path=/products/**

        # 3. Microservicio de Wishlist y su Historial
        - id: wishlist-service
          uri: http://localhost:8083   # Puerto de wishlist que vimos en tus pruebas
          predicates:
            - Path=/api/v1/wishlist/**